name: Build Docs (PR)

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Free space in hosted agent
      run: |
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          
    - uses: actions/checkout@v2

    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && apt-get install -y pandoc"
        docs-folder: "docs/"

    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended imagemagick"
        build-command: "make latexpdf"
        docs-folder: "docs/"

    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v2
      if: "contains(github.event.head_commit.message, 'save artifact')"
      with:
        name: DocumentationHTML
        path: docs/build/html/

    # Create an artifact out of the previously built pdf.
    - uses: actions/upload-artifact@v2
      if: "contains(github.event.head_commit.message, 'save artifact')"
      with:
        name: Documentation
        path: docs/build/latex/tfwatcher.pdf
